### ISSUE TITLE
Please add support for sway

### ISSUE THREAD

**Issue by msrd0** [LuckyTurtleDev/more-wallpapers#2]
Here's an example on how it works in bash script: https://gitlab.com/msrd0/dotfiles/-/blob/master/HOME/.config/sway/catbg.sh#L13

**Comment by Lukas1818** [comment]
pull request are welcome

**Comment by LuckyTurtleDev** [comment]
Sway is already supported by using the `wallpaper` feature flag. But it does currently not support setting a different wallpaper per screen.
Do you want to work on this?
